theme: jekyll-theme-cayman

# Site settings
title: Ziying Feng
email: ziyingfeng@ucla.edu
description: "Ziying Feng - Github Page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ziying Feng
  pic: 
  position: PhD student @ University of California los Angeles
  social:
  
  - title: linkedin
    url:  https://www.linkedin.com/in/ziying-feng-5337a8121/
  - title: github
    url: http://github.com/ZiyingFeng

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  
  - title: linkedin
    url:  https://www.linkedin.com/in/ziying-feng-5337a8121/
  - title: github
    url: http://github.com/ZiyingFeng

# Postal address (add as many lines as necessary)
address:
  - line: 500 Landfair Ave
  - line: Los Angeles, CA 90024

# Build settings
markdown: kramdown
permalink: pretty
